"""Karbo — Official Python SDK for KarboAI Bot API."""

from .buttons import (
    Button,
    ButtonPress,
    ButtonStyle,
    ConfettiParticles,
    Glitch,
    Gradient,
    HeartParticles,
    Neon,
    Outline,
    Particles,
    PixelParticles,
    Pulse,
    SmokeParticles,
    SparkParticles,
    SwipeInteraction,
    TapInteraction,
    buttons_to_dict,
)
from .client import KarboBot
from .errors import (
    APIError,
    AuthenticationError,
    ForbiddenError,
    KarboError,
    NotFoundError,
    RateLimitError,
    ValidationError,
)
from .models import (
    CHAT_TYPE_BOT,
    CHAT_TYPE_PM,
    CHAT_TYPE_PRIVATE,
    CHAT_TYPE_PUBLIC,
    NORMAL_MESSAGE,
    JOIN_CHAT_MESSAGE,
    LEAVE_CHAT_MESSAGE,
    KICK_CHAT_MESSAGE,
    CREATE_CHAT_MESSAGE,
    USER_DELETED_MESSAGE,
    ADMIN_DELETED_MESSAGE,
    VOICE_CHAT_STARTED,
    VOICE_CHAT_ENDED,
    BACKGROUND_CHANGED,
    INVITED_USER_TO_CHAT,
    INVITED_BOT_TO_CHAT,
    AvatarFrame,
    Author,
    BotInfo,
    Chat,
    LastMessagePreview,
    Member,
    Message,
    MessageReaction,
    SentMessage,
    User,
)
from .ws import KarboBotWS

__all__ = [
    "KarboBot",
    "KarboBotWS",
    # Models
    "AvatarFrame",
    "Author",
    "BotInfo",
    "Chat",
    "LastMessagePreview",
    "Member",
    "Message",
    "MessageReaction",
    "SentMessage",
    "User",
    # Chat type constants
    "CHAT_TYPE_PUBLIC",
    "CHAT_TYPE_BOT",
    "CHAT_TYPE_PM",
    "CHAT_TYPE_PRIVATE",
    # Message type constants (most-used subset)
    "NORMAL_MESSAGE",
    "JOIN_CHAT_MESSAGE",
    "LEAVE_CHAT_MESSAGE",
    "KICK_CHAT_MESSAGE",
    "CREATE_CHAT_MESSAGE",
    "USER_DELETED_MESSAGE",
    "ADMIN_DELETED_MESSAGE",
    "VOICE_CHAT_STARTED",
    "VOICE_CHAT_ENDED",
    "BACKGROUND_CHANGED",
    "INVITED_USER_TO_CHAT",
    "INVITED_BOT_TO_CHAT",
    # Buttons API
    "Button",
    "ButtonPress",
    "ButtonStyle",
    "Gradient",
    "TapInteraction",
    "SwipeInteraction",
    "Pulse",
    "Neon",
    "Glitch",
    "Outline",
    "Particles",
    "SparkParticles",
    "ConfettiParticles",
    "HeartParticles",
    "PixelParticles",
    "SmokeParticles",
    "buttons_to_dict",
    # Errors
    "KarboError",
    "AuthenticationError",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitError",
    "ValidationError",
    "APIError",
]

__version__ = "0.9.0"
